//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.6.0.457
//      for file genesis_dotnet\Genesis.NET\Entities\Responses\Successful\BlacklistSuccessResponse.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace Genesis.Net.Entities.Responses.Successful
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public partial class BlacklistSuccessResponse : pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.Genesis.Net.Entities.Responses.BlacklistModel.IBlacklistModelRequirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.BlacklistModel>
	{
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public __pMixinAutoGenerated.Genesis_Net_Entities_Responses_BlacklistModel.BlacklistModelMasterWrapper Genesis_Net_Entities_Responses_BlacklistModel;
			public __Mixins (BlacklistSuccessResponse target)
			{
				Genesis_Net_Entities_Responses_BlacklistModel = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.Genesis_Net_Entities_Responses_BlacklistModel.BlacklistModelMasterWrapper> ((pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.Genesis.Net.Entities.Responses.BlacklistModel.IBlacklistModelRequirements)target);
			}
			[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse target)
			{
				Genesis_Net_Entities_Responses_BlacklistModel.__ActivateMixinDependencies (target);
			}
		}
		private sealed class __pMixinAutoGenerated
		{
			public sealed class Genesis_Net_Entities_Responses_BlacklistModel
			{
				public class BlacklistModelMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public BlacklistModelMasterWrapper (pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.Genesis.Net.Entities.Responses.BlacklistModel.IBlacklistModelRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.Genesis.Net.Entities.Responses.BlacklistModel.BlacklistModelAbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::Genesis.Net.Entities.Responses.BlacklistModel _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.Boolean Blacklisted {
						get {
							return base.ExecutePropertyGet ("Blacklisted", () => _mixinInstance.Blacklisted);
						}
						set {
							base.ExecutePropertySet ("Blacklisted", value, v => _mixinInstance.Blacklisted = v);
						}
					}
				}
			}
		}
		private __Mixins ____mixins;
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		private __Mixins __mixins {
			get {
				if (null == ____mixins) {
					lock (__Mixins.____Lock) {
						if (null == ____mixins) {
							____mixins = new __Mixins (this);
							____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return ____mixins;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::Genesis.Net.Entities.Responses.BlacklistModel global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.BlacklistModel>.MixinInstance {
			get {
				return __mixins.Genesis_Net_Entities_Responses_BlacklistModel._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "blacklisted")]
		public global::System.Boolean Blacklisted {
			get {
				return __mixins.Genesis_Net_Entities_Responses_BlacklistModel.Blacklisted;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_BlacklistModel.Blacklisted = value;
			}
		}
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.__Shared
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.Genesis.Net.Entities.Responses.BlacklistModel
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface IBlacklistModelRequirements : global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.Genesis.Net.Entities.Responses.BlacklistModel
{
	internal abstract class BlacklistModelProtectedMembersWrapper : global::Genesis.Net.Entities.Responses.BlacklistModel
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.Genesis.Net.Entities.Responses.BlacklistModel
{
	internal class BlacklistModelAbstractWrapper : BlacklistModelProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.Genesis.Net.Entities.Responses.BlacklistModel.IBlacklistModelRequirements _target;
		public BlacklistModelAbstractWrapper (global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Successful.BlacklistSuccessResponse.Genesis.Net.Entities.Responses.BlacklistModel.IBlacklistModelRequirements target) : base ()
		{
			_target = target;
		}
	}
}
