//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesis.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genesis.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer account data invalid, please contact support..
        /// </summary>
        internal static string AccountError {
            get {
                return ResourceManager.GetString("AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Check your API credentials..
        /// </summary>
        internal static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Verification failed..
        /// </summary>
        internal static string AvsError {
            get {
                return ResourceManager.GetString("AvsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIN blacklisted..
        /// </summary>
        internal static string BinBlacklistError {
            get {
                return ResourceManager.GetString("BinBlacklistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card bin does not match billing country.
        /// </summary>
        internal static string BinCountryCheckError {
            get {
                return ResourceManager.GetString("BinCountryCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value from payment transaction or risk params is blacklisted..
        /// </summary>
        internal static string BlacklistError {
            get {
                return ResourceManager.GetString("BlacklistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card is blacklisted.
        /// </summary>
        internal static string CardBlacklistError {
            get {
                return ResourceManager.GetString("CardBlacklistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card limit exceeded configured limits..
        /// </summary>
        internal static string CardLimitExceededError {
            get {
                return ResourceManager.GetString("CardLimitExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticketsize by unknown card exceeded!.
        /// </summary>
        internal static string CardTicketSizeExceededError {
            get {
                return ResourceManager.GetString("CardTicketSizeExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity by unknown card exceeded!.
        /// </summary>
        internal static string CardVelocityExceededError {
            get {
                return ResourceManager.GetString("CardVelocityExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Whitelist Filter blocked the transaction. This filter - like the above one - uses the PAN blacklist (BL) to perform CC number checks against the BL in the DB. This filter however will reject transactions from a CC with a number which is not whitelisted..
        /// </summary>
        internal static string CardWhitelistError {
            get {
                return ResourceManager.GetString("CardWhitelistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENTATION MISSING.
        /// </summary>
        internal static string ChargebackNotFoundError {
            get {
                return ResourceManager.GetString("ChargebackNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with issuer failed, please contact sup- port..
        /// </summary>
        internal static string CommunicationError {
            get {
                return ResourceManager.GetString("CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error occured, e.g. terminal not config- ured properly. Check terminal settings..
        /// </summary>
        internal static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to issuer could not be established, please contact support..
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MID limits exceeded..
        /// </summary>
        internal static string ContractLimitExceededError {
            get {
                return ResourceManager.GetString("ContractLimitExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country blacklisted..
        /// </summary>
        internal static string CountryBlacklistError {
            get {
                return ResourceManager.GetString("CountryBlacklistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount excceds credit card limit..
        /// </summary>
        internal static string CreditExceededError {
            get {
                return ResourceManager.GetString("CreditExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CrossSellingFilter blocks duplicated transactions when an approved transaction has been found on an- other mid. That is, if the transaction has already been processed successfully on a di↵erent mid and within the specified time frame, context entity / scope and possibly within the issuer scope (or not), it will be rejected in order to prevent duplicates..
        /// </summary>
        internal static string CSDetectionError {
            get {
                return ResourceManager.GetString("CSDetectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction doublet was detected, transaction was blocked. This happens if several transactions with same amount, card holder, cc number, cvv and expiry date are sent within 5 minutes..
        /// </summary>
        internal static string DoubletTransactionError {
            get {
                return ResourceManager.GetString("DoubletTransactionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined, expiration date not in the future or date invalid..
        /// </summary>
        internal static string ExpiredCardError {
            get {
                return ResourceManager.GetString("ExpiredCardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid were data sent to the API..
        /// </summary>
        internal static string InputDataError {
            get {
                return ResourceManager.GetString("InputDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument passed in invalid format. Check parame- ters..
        /// </summary>
        internal static string InputDataFormatError {
            get {
                return ResourceManager.GetString("InputDataFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument passed in valid format but makes no sense (e.g. incorrect country code or currency). Check pa- rameters..
        /// </summary>
        internal static string InputDataInvalidError {
            get {
                return ResourceManager.GetString("InputDataInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument is missing. Check parameters..
        /// </summary>
        internal static string InputDataMissingError {
            get {
                return ResourceManager.GetString("InputDataMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined, Credit card number is invalid..
        /// </summary>
        internal static string InvalidCardError {
            get {
                return ResourceManager.GetString("InvalidCardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENTATION MISSING.
        /// </summary>
        internal static string InvalidContentTypeError {
            get {
                return ResourceManager.GetString("InvalidContentTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction type was passed to API..
        /// </summary>
        internal static string InvalidTransactionTypeError {
            get {
                return ResourceManager.GetString("InvalidTransactionTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input XML could not be parsed due to invalid code. Please check XML data..
        /// </summary>
        internal static string InvalidXmlError {
            get {
                return ResourceManager.GetString("InvalidXmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address blacklisted..
        /// </summary>
        internal static string IpBlacklistError {
            get {
                return ResourceManager.GetString("IpBlacklistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is undergoing maintenance, request could not be handled..
        /// </summary>
        internal static string MaintenanceError {
            get {
                return ResourceManager.GetString("MaintenanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a transaction is considered high risk by MaxMind minFraud service, a MaxMindRiskError is raised..
        /// </summary>
        internal static string MaxMindRiskError {
            get {
                return ResourceManager.GetString("MaxMindRiskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found user transaction declined by issuer. Try again later!.
        /// </summary>
        internal static string MultipleFailureDetectionError {
            get {
                return ResourceManager.GetString("MultipleFailureDetectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer response could not be parsed - please reconcile and contact support..
        /// </summary>
        internal static string ParsingError {
            get {
                return ResourceManager.GetString("ParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined by issuer.
        /// </summary>
        internal static string ProcessingError {
            get {
                return ResourceManager.GetString("ProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount/count by recurring subscription exceeded..
        /// </summary>
        internal static string RecurringLimitExceededError {
            get {
                return ResourceManager.GetString("RecurringLimitExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference transaction already invalidated!.
        /// </summary>
        internal static string ReferenceInvalidatedError {
            get {
                return ResourceManager.GetString("ReferenceInvalidatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data mismatch with reference, e.g. amount exceeds reference.
        /// </summary>
        internal static string ReferenceMismatchError {
            get {
                return ResourceManager.GetString("ReferenceMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference transaction was not found..
        /// </summary>
        internal static string ReferenceNotFoundError {
            get {
                return ResourceManager.GetString("ReferenceNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Workflow specified..
        /// </summary>
        internal static string ReferenceWorkflowError {
            get {
                return ResourceManager.GetString("ReferenceWorkflowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer configuration error.
        /// </summary>
        internal static string RemoteConfigurationError {
            get {
                return ResourceManager.GetString("RemoteConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer could not reach clearing network.
        /// </summary>
        internal static string RemoteConnectionError {
            get {
                return ResourceManager.GetString("RemoteConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some passed data caused an error on the issuer.
        /// </summary>
        internal static string RemoteDataError {
            get {
                return ResourceManager.GetString("RemoteDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured on the issuer. Contact support..
        /// </summary>
        internal static string RemoteError {
            get {
                return ResourceManager.GetString("RemoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured on the issuer.
        /// </summary>
        internal static string RemoteSystemError {
            get {
                return ResourceManager.GetString("RemoteSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer has timeouted with clearing network.
        /// </summary>
        internal static string RemoteTimeoutError {
            get {
                return ResourceManager.GetString("RemoteTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote workflow error.
        /// </summary>
        internal static string RemoteWorkflowError {
            get {
                return ResourceManager.GetString("RemoteWorkflowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer returned invalid response - please reconcile and contact support.
        /// </summary>
        internal static string ResponseError {
            get {
                return ResourceManager.GetString("ResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENTATION MISSING.
        /// </summary>
        internal static string RetrievalRequestNotFoundError {
            get {
                return ResourceManager.GetString("RetrievalRequestNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined by risk management.
        /// </summary>
        internal static string RiskError {
            get {
                return ResourceManager.GetString("RiskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general system error occured.
        /// </summary>
        internal static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal limits exceeded..
        /// </summary>
        internal static string TerminalLimitExceededError {
            get {
                return ResourceManager.GetString("TerminalLimitExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined by ThreatMetrix risk module..
        /// </summary>
        internal static string ThreatMetrixRiskError {
            get {
                return ResourceManager.GetString("ThreatMetrixRiskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer does not respond within given timeframe - please reconcile.
        /// </summary>
        internal static string TimeoutError {
            get {
                return ResourceManager.GetString("TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced transaction could not be found..
        /// </summary>
        internal static string TransactionNotFoundError {
            get {
                return ResourceManager.GetString("TransactionNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction pending..
        /// </summary>
        internal static string TransactionPendingError {
            get {
                return ResourceManager.GetString("TransactionPendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined error..
        /// </summary>
        internal static string UndefinedError {
            get {
                return ResourceManager.GetString("UndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User limit exceeded configured limits..
        /// </summary>
        internal static string UserLimitExceededError {
            get {
                return ResourceManager.GetString("UserLimitExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transaction was triggered that is not possible at this time in the workflow, e.g. a refund on a declined transaction..
        /// </summary>
        internal static string WorkflowError {
            get {
                return ResourceManager.GetString("WorkflowError", resourceCulture);
            }
        }
    }
}
