//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.6.0.457
//      for file genesis_dotnet\Genesis.NET\Entities\Responses\Error\SingleReconcileErrorResponse.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace Genesis.Net.Entities.Responses.Error
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public partial class SingleReconcileErrorResponse : pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.TransactionStatusModel.ITransactionStatusModelRequirements, pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.ErrorModel.IErrorModelRequirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.TransactionStatusModel>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.ErrorModel>
	{
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public __pMixinAutoGenerated.Genesis_Net_Entities_Responses_TransactionStatusModel.TransactionStatusModelMasterWrapper Genesis_Net_Entities_Responses_TransactionStatusModel;
			public __pMixinAutoGenerated.Genesis_Net_Entities_Responses_ErrorModel.ErrorModelMasterWrapper Genesis_Net_Entities_Responses_ErrorModel;
			public __Mixins (SingleReconcileErrorResponse target)
			{
				Genesis_Net_Entities_Responses_TransactionStatusModel = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.Genesis_Net_Entities_Responses_TransactionStatusModel.TransactionStatusModelMasterWrapper> ((pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.TransactionStatusModel.ITransactionStatusModelRequirements)target);
				Genesis_Net_Entities_Responses_ErrorModel = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.Genesis_Net_Entities_Responses_ErrorModel.ErrorModelMasterWrapper> ((pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.ErrorModel.IErrorModelRequirements)target);
			}
			[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse target)
			{
				Genesis_Net_Entities_Responses_TransactionStatusModel.__ActivateMixinDependencies (target);
				Genesis_Net_Entities_Responses_ErrorModel.__ActivateMixinDependencies (target);
			}
		}
		private sealed class __pMixinAutoGenerated
		{
			public sealed class Genesis_Net_Entities_Responses_TransactionStatusModel
			{
				public class TransactionStatusModelMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public TransactionStatusModelMasterWrapper (pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.TransactionStatusModel.ITransactionStatusModelRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.TransactionStatusModel.TransactionStatusModelAbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::Genesis.Net.Entities.Responses.TransactionStatusModel _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String Status {
						get {
							return base.ExecutePropertyGet ("Status", () => _mixinInstance.Status);
						}
						set {
							base.ExecutePropertySet ("Status", value, v => _mixinInstance.Status = v);
						}
					}
				}
			}
			public sealed class Genesis_Net_Entities_Responses_ErrorModel
			{
				public class ErrorModelMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public ErrorModelMasterWrapper (pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.ErrorModel.IErrorModelRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.ErrorModel.ErrorModelAbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::Genesis.Net.Entities.Responses.ErrorModel _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::Genesis.Net.Errors.ErrorCodes Code {
						get {
							return base.ExecutePropertyGet ("Code", () => _mixinInstance.Code);
						}
						set {
							base.ExecutePropertySet ("Code", value, v => _mixinInstance.Code = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.Int32 ProxyCode {
						get {
							return base.ExecutePropertyGet ("ProxyCode", () => _mixinInstance.ProxyCode);
						}
						set {
							base.ExecutePropertySet ("ProxyCode", value, v => _mixinInstance.ProxyCode = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String TechnicalMessage {
						get {
							return base.ExecutePropertyGet ("TechnicalMessage", () => _mixinInstance.TechnicalMessage);
						}
						set {
							base.ExecutePropertySet ("TechnicalMessage", value, v => _mixinInstance.TechnicalMessage = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String Message {
						get {
							return base.ExecutePropertyGet ("Message", () => _mixinInstance.Message);
						}
						set {
							base.ExecutePropertySet ("Message", value, v => _mixinInstance.Message = v);
						}
					}
				}
			}
		}
		private __Mixins ____mixins;
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		private __Mixins __mixins {
			get {
				if (null == ____mixins) {
					lock (__Mixins.____Lock) {
						if (null == ____mixins) {
							____mixins = new __Mixins (this);
							____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return ____mixins;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::Genesis.Net.Entities.Responses.TransactionStatusModel global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.TransactionStatusModel>.MixinInstance {
			get {
				return __mixins.Genesis_Net_Entities_Responses_TransactionStatusModel._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::Genesis.Net.Entities.Responses.ErrorModel global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.ErrorModel>.MixinInstance {
			get {
				return __mixins.Genesis_Net_Entities_Responses_ErrorModel._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "status")]
		public global::System.String Status {
			get {
				return __mixins.Genesis_Net_Entities_Responses_TransactionStatusModel.Status;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_TransactionStatusModel.Status = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlIgnoreAttribute]
		public global::Genesis.Net.Errors.ErrorCodes Code {
			get {
				return __mixins.Genesis_Net_Entities_Responses_ErrorModel.Code;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_ErrorModel.Code = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "code")]
		public global::System.Int32 ProxyCode {
			get {
				return __mixins.Genesis_Net_Entities_Responses_ErrorModel.ProxyCode;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_ErrorModel.ProxyCode = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "technical_message")]
		public global::System.String TechnicalMessage {
			get {
				return __mixins.Genesis_Net_Entities_Responses_ErrorModel.TechnicalMessage;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_ErrorModel.TechnicalMessage = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "message")]
		public global::System.String Message {
			get {
				return __mixins.Genesis_Net_Entities_Responses_ErrorModel.Message;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_ErrorModel.Message = value;
			}
		}
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.__Shared
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.TransactionStatusModel
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ITransactionStatusModelRequirements : global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.TransactionStatusModel
{
	internal abstract class TransactionStatusModelProtectedMembersWrapper : global::Genesis.Net.Entities.Responses.TransactionStatusModel
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.TransactionStatusModel
{
	internal class TransactionStatusModelAbstractWrapper : TransactionStatusModelProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.TransactionStatusModel.ITransactionStatusModelRequirements _target;
		public TransactionStatusModelAbstractWrapper (global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.TransactionStatusModel.ITransactionStatusModelRequirements target) : base ()
		{
			_target = target;
		}
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.ErrorModel
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface IErrorModelRequirements : global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.ErrorModel
{
	internal abstract class ErrorModelProtectedMembersWrapper : global::Genesis.Net.Entities.Responses.ErrorModel
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.ErrorModel
{
	internal class ErrorModelAbstractWrapper : ErrorModelProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.ErrorModel.IErrorModelRequirements _target;
		public ErrorModelAbstractWrapper (global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.Error.SingleReconcileErrorResponse.Genesis.Net.Entities.Responses.ErrorModel.IErrorModelRequirements target) : base ()
		{
			_target = target;
		}
	}
}
