using Genesis.Net.Entities.Attributes.Request.Financial.Cards.ThreedsV2.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Serialization;

namespace Genesis.Net.Entities.Attributes.Request.Financial.Cards.ThreedsV2
{
    /// <summary>
    /// For application-based transactions. They are all required in case the device_type is set to application. See <see cref="Control.DeviceType"/>
    /// </summary>
    [XmlRoot(ElementName = "sdk")]
    public partial class Sdk : Entity
    {
        /// <summary>
        /// SDK Interface types that the device of the consumer supports for displaying specific challenge interfaces within the SDK.
        /// </summary>
        [XmlElement(ElementName = "interface")]
        public Interfaces Interface { get; set; }

        /// <remarks/>
        [XmlArray("ui_types")]
        [XmlArrayItem(typeof(UiTypes), ElementName = "ui_type")]
        public List<UiTypes> UiTypes { get; set; }

        /// <summary>
        /// Universally unique ID created upon all installations and updates of the 3DS Requestor APp on a Customer Device.
        /// This will be newly generated and stored by the 3DS SDK for each installation or update.
        /// The field is limited to 36 characters and it shall have a canonical format as defined in IETF RFC 4122.
        /// </summary>
        [XmlElement(ElementName = "application_id")]
        public Guid ApplicationId { get; set; }

        /// <summary>
        /// JWE Object as defined Section 6.2.2.1 containing data encrypted by the SDK for the DS to decrypt.
        /// The data will be present when sending to DS, but not present from DS to ACS.
        /// </summary>
        [MaxLength(64000)]
        [XmlElement(ElementName = "encrypted_data")]
        public string EncryptedData { get; set; }

        /// <summary>
        /// Public key component of the ephemeral key pair generated by the 3DS SDK and used to establish session keys between the 3DS SDK and ACS.
        /// In AReq, this data element is contained within the ACS Signed Content JWS Object.
        /// The field is limited to maximum 256 characters.
        /// </summary>
        [MaxLength(256)]
        [XmlElement(ElementName = "ephemeral_public_key_pair")]
        public string EphemeralPublicKeyPair { get; set; }

        /// <summary>
        /// Indicates the maximum amount of time (in minutes) for all exchanges. The field shall have value greater or equals than 05.
        /// </summary>
        [Range(5, int.MaxValue)]
        [XmlElement(ElementName = "max_timeout")]
        public int MaxTimeout { get; set; }

        /// <summary>
        /// Identifies the vendor and version of the 3DS SDK that is integrated in a 3DS Requestor App, assigned by EMVCo when the 3DS SDK is approved.
        /// The field is limited to 32 characters.
        /// </summary>
        [MaxLength(32)]
        [XmlElement(ElementName = "reference_number")]
        public string ReferenceNumber { get; set; }
    }
}
