//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.6.0.457
//      for file genesis_dotnet\Genesis.NET\Entities\Responses\ChargebackResponse.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace Genesis.Net.Entities.Responses
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public partial class ChargebackResponse : pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.Genesis.Net.Entities.Responses.MoneyModel.IMoneyModelRequirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.MoneyModel>
	{
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public __pMixinAutoGenerated.Genesis_Net_Entities_Responses_MoneyModel.MoneyModelMasterWrapper Genesis_Net_Entities_Responses_MoneyModel;
			public __Mixins (ChargebackResponse target)
			{
				Genesis_Net_Entities_Responses_MoneyModel = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.Genesis_Net_Entities_Responses_MoneyModel.MoneyModelMasterWrapper> ((pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.Genesis.Net.Entities.Responses.MoneyModel.IMoneyModelRequirements)target);
			}
			[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.ChargebackResponse target)
			{
				Genesis_Net_Entities_Responses_MoneyModel.__ActivateMixinDependencies (target);
			}
		}
		private sealed class __pMixinAutoGenerated
		{
			public sealed class Genesis_Net_Entities_Responses_MoneyModel
			{
				public class MoneyModelMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public MoneyModelMasterWrapper (pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.Genesis.Net.Entities.Responses.MoneyModel.IMoneyModelRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.Genesis.Net.Entities.Responses.MoneyModel.MoneyModelAbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::Genesis.Net.Entities.Responses.MoneyModel _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.ChargebackResponse target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.Decimal Amount {
						get {
							return base.ExecutePropertyGet ("Amount", () => _mixinInstance.Amount);
						}
						set {
							base.ExecutePropertySet ("Amount", value, v => _mixinInstance.Amount = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String ProxyAmount {
						get {
							return base.ExecutePropertyGet ("ProxyAmount", () => _mixinInstance.ProxyAmount);
						}
						set {
							base.ExecutePropertySet ("ProxyAmount", value, v => _mixinInstance.ProxyAmount = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::Genesis.Net.Common.Iso4217CurrencyCodes Currency {
						get {
							return base.ExecutePropertyGet ("Currency", () => _mixinInstance.Currency);
						}
						set {
							base.ExecutePropertySet ("Currency", value, v => _mixinInstance.Currency = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.Nullable<global::System.Boolean> PartialApproval {
						get {
							return base.ExecutePropertyGet ("PartialApproval", () => _mixinInstance.PartialApproval);
						}
						set {
							base.ExecutePropertySet ("PartialApproval", value, v => _mixinInstance.PartialApproval = v);
						}
					}
				}
			}
		}
		private __Mixins ____mixins;
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		private __Mixins __mixins {
			get {
				if (null == ____mixins) {
					lock (__Mixins.____Lock) {
						if (null == ____mixins) {
							____mixins = new __Mixins (this);
							____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return ____mixins;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::Genesis.Net.Entities.Responses.MoneyModel global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.MoneyModel>.MixinInstance {
			get {
				return __mixins.Genesis_Net_Entities_Responses_MoneyModel._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlIgnoreAttribute]
		public global::System.Decimal Amount {
			get {
				return __mixins.Genesis_Net_Entities_Responses_MoneyModel.Amount;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_MoneyModel.Amount = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "amount")]
		public global::System.String ProxyAmount {
			get {
				return __mixins.Genesis_Net_Entities_Responses_MoneyModel.ProxyAmount;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_MoneyModel.ProxyAmount = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "currency")]
		public global::Genesis.Net.Common.Iso4217CurrencyCodes Currency {
			get {
				return __mixins.Genesis_Net_Entities_Responses_MoneyModel.Currency;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_MoneyModel.Currency = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "partial_approval")]
		public global::System.Nullable<global::System.Boolean> PartialApproval {
			get {
				return __mixins.Genesis_Net_Entities_Responses_MoneyModel.PartialApproval;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_MoneyModel.PartialApproval = value;
			}
		}
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.__Shared
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.Genesis.Net.Entities.Responses.MoneyModel
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface IMoneyModelRequirements : global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.Genesis.Net.Entities.Responses.MoneyModel
{
	internal abstract class MoneyModelProtectedMembersWrapper : global::Genesis.Net.Entities.Responses.MoneyModel
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.Genesis.Net.Entities.Responses.MoneyModel
{
	internal class MoneyModelAbstractWrapper : MoneyModelProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.Genesis.Net.Entities.Responses.MoneyModel.IMoneyModelRequirements _target;
		public MoneyModelAbstractWrapper (global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.ChargebackResponse.Genesis.Net.Entities.Responses.MoneyModel.IMoneyModelRequirements target) : base ()
		{
			_target = target;
		}
	}
}
