//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.6.0.457
//      for file genesis_dotnet\Genesis.NET\Entities\Responses\RetrievalResponse.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace Genesis.Net.Entities.Responses
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public partial class RetrievalResponse : pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.AuthorizationModel.IAuthorizationModelRequirements, pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.TransactionTypeModel.ITransactionTypeModelRequirements, pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.CustomerModel.ICustomerModelRequirements, pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.RetrievalResponseModel.IRetrievalResponseModelRequirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.AuthorizationModel>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.TransactionTypeModel>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.CustomerModel>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.RetrievalResponseModel>
	{
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public __pMixinAutoGenerated.Genesis_Net_Entities_Responses_AuthorizationModel.AuthorizationModelMasterWrapper Genesis_Net_Entities_Responses_AuthorizationModel;
			public __pMixinAutoGenerated.Genesis_Net_Entities_Responses_TransactionTypeModel.TransactionTypeModelMasterWrapper Genesis_Net_Entities_Responses_TransactionTypeModel;
			public __pMixinAutoGenerated.Genesis_Net_Entities_Responses_CustomerModel.CustomerModelMasterWrapper Genesis_Net_Entities_Responses_CustomerModel;
			public __pMixinAutoGenerated.Genesis_Net_Entities_Responses_RetrievalResponseModel.RetrievalResponseModelMasterWrapper Genesis_Net_Entities_Responses_RetrievalResponseModel;
			public __Mixins (RetrievalResponse target)
			{
				Genesis_Net_Entities_Responses_AuthorizationModel = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.Genesis_Net_Entities_Responses_AuthorizationModel.AuthorizationModelMasterWrapper> ((pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.AuthorizationModel.IAuthorizationModelRequirements)target);
				Genesis_Net_Entities_Responses_TransactionTypeModel = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.Genesis_Net_Entities_Responses_TransactionTypeModel.TransactionTypeModelMasterWrapper> ((pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.TransactionTypeModel.ITransactionTypeModelRequirements)target);
				Genesis_Net_Entities_Responses_CustomerModel = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.Genesis_Net_Entities_Responses_CustomerModel.CustomerModelMasterWrapper> ((pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.CustomerModel.ICustomerModelRequirements)target);
				Genesis_Net_Entities_Responses_RetrievalResponseModel = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.Genesis_Net_Entities_Responses_RetrievalResponseModel.RetrievalResponseModelMasterWrapper> ((pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.RetrievalResponseModel.IRetrievalResponseModelRequirements)target);
			}
			[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.RetrievalResponse target)
			{
				Genesis_Net_Entities_Responses_AuthorizationModel.__ActivateMixinDependencies (target);
				Genesis_Net_Entities_Responses_TransactionTypeModel.__ActivateMixinDependencies (target);
				Genesis_Net_Entities_Responses_CustomerModel.__ActivateMixinDependencies (target);
				Genesis_Net_Entities_Responses_RetrievalResponseModel.__ActivateMixinDependencies (target);
			}
		}
		private sealed class __pMixinAutoGenerated
		{
			public sealed class Genesis_Net_Entities_Responses_AuthorizationModel
			{
				public class AuthorizationModelMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public AuthorizationModelMasterWrapper (pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.AuthorizationModel.IAuthorizationModelRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.AuthorizationModel.AuthorizationModelAbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::Genesis.Net.Entities.Responses.AuthorizationModel _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.RetrievalResponse target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String AuthorizationCode {
						get {
							return base.ExecutePropertyGet ("AuthorizationCode", () => _mixinInstance.AuthorizationCode);
						}
						set {
							base.ExecutePropertySet ("AuthorizationCode", value, v => _mixinInstance.AuthorizationCode = v);
						}
					}
				}
			}
			public sealed class Genesis_Net_Entities_Responses_TransactionTypeModel
			{
				public class TransactionTypeModelMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public TransactionTypeModelMasterWrapper (pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.TransactionTypeModel.ITransactionTypeModelRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.TransactionTypeModel.TransactionTypeModelAbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::Genesis.Net.Entities.Responses.TransactionTypeModel _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.RetrievalResponse target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::Genesis.Net.TransactionTypes TransactionType {
						get {
							return base.ExecutePropertyGet ("TransactionType", () => _mixinInstance.TransactionType);
						}
						set {
							base.ExecutePropertySet ("TransactionType", value, v => _mixinInstance.TransactionType = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String ProxyTransactionType {
						get {
							return base.ExecutePropertyGet ("ProxyTransactionType", () => _mixinInstance.ProxyTransactionType);
						}
						set {
							base.ExecutePropertySet ("ProxyTransactionType", value, v => _mixinInstance.ProxyTransactionType = v);
						}
					}
				}
			}
			public sealed class Genesis_Net_Entities_Responses_CustomerModel
			{
				public class CustomerModelMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public CustomerModelMasterWrapper (pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.CustomerModel.ICustomerModelRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.CustomerModel.CustomerModelAbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::Genesis.Net.Entities.Responses.CustomerModel _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.RetrievalResponse target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String CustomerEmail {
						get {
							return base.ExecutePropertyGet ("CustomerEmail", () => _mixinInstance.CustomerEmail);
						}
						set {
							base.ExecutePropertySet ("CustomerEmail", value, v => _mixinInstance.CustomerEmail = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String CustomerPhone {
						get {
							return base.ExecutePropertyGet ("CustomerPhone", () => _mixinInstance.CustomerPhone);
						}
						set {
							base.ExecutePropertySet ("CustomerPhone", value, v => _mixinInstance.CustomerPhone = v);
						}
					}
				}
			}
			public sealed class Genesis_Net_Entities_Responses_RetrievalResponseModel
			{
				public class RetrievalResponseModelMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public RetrievalResponseModelMasterWrapper (pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.RetrievalResponseModel.IRetrievalResponseModelRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.RetrievalResponseModel.RetrievalResponseModelAbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::Genesis.Net.Entities.Responses.RetrievalResponseModel _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (Genesis.Net.Entities.Responses.RetrievalResponse target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String Type {
						get {
							return base.ExecutePropertyGet ("Type", () => _mixinInstance.Type);
						}
						set {
							base.ExecutePropertySet ("Type", value, v => _mixinInstance.Type = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String Arn {
						get {
							return base.ExecutePropertyGet ("Arn", () => _mixinInstance.Arn);
						}
						set {
							base.ExecutePropertySet ("Arn", value, v => _mixinInstance.Arn = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.DateTime PostDate {
						get {
							return base.ExecutePropertyGet ("PostDate", () => _mixinInstance.PostDate);
						}
						set {
							base.ExecutePropertySet ("PostDate", value, v => _mixinInstance.PostDate = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String ProxyPostDate {
						get {
							return base.ExecutePropertyGet ("ProxyPostDate", () => _mixinInstance.ProxyPostDate);
						}
						set {
							base.ExecutePropertySet ("ProxyPostDate", value, v => _mixinInstance.ProxyPostDate = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String ReasonCode {
						get {
							return base.ExecutePropertyGet ("ReasonCode", () => _mixinInstance.ReasonCode);
						}
						set {
							base.ExecutePropertySet ("ReasonCode", value, v => _mixinInstance.ReasonCode = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String ReasonDescription {
						get {
							return base.ExecutePropertyGet ("ReasonDescription", () => _mixinInstance.ReasonDescription);
						}
						set {
							base.ExecutePropertySet ("ReasonDescription", value, v => _mixinInstance.ReasonDescription = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String CardNumber {
						get {
							return base.ExecutePropertyGet ("CardNumber", () => _mixinInstance.CardNumber);
						}
						set {
							base.ExecutePropertySet ("CardNumber", value, v => _mixinInstance.CardNumber = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String CardBrand {
						get {
							return base.ExecutePropertyGet ("CardBrand", () => _mixinInstance.CardBrand);
						}
						set {
							base.ExecutePropertySet ("CardBrand", value, v => _mixinInstance.CardBrand = v);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String OriginalTransactionUniqueId {
						get {
							return base.ExecutePropertyGet ("OriginalTransactionUniqueId", () => _mixinInstance.OriginalTransactionUniqueId);
						}
						set {
							base.ExecutePropertySet ("OriginalTransactionUniqueId", value, v => _mixinInstance.OriginalTransactionUniqueId = v);
						}
					}
				}
			}
		}
		private __Mixins ____mixins;
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		private __Mixins __mixins {
			get {
				if (null == ____mixins) {
					lock (__Mixins.____Lock) {
						if (null == ____mixins) {
							____mixins = new __Mixins (this);
							____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return ____mixins;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::Genesis.Net.Entities.Responses.AuthorizationModel global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.AuthorizationModel>.MixinInstance {
			get {
				return __mixins.Genesis_Net_Entities_Responses_AuthorizationModel._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::Genesis.Net.Entities.Responses.TransactionTypeModel global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.TransactionTypeModel>.MixinInstance {
			get {
				return __mixins.Genesis_Net_Entities_Responses_TransactionTypeModel._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::Genesis.Net.Entities.Responses.CustomerModel global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.CustomerModel>.MixinInstance {
			get {
				return __mixins.Genesis_Net_Entities_Responses_CustomerModel._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::Genesis.Net.Entities.Responses.RetrievalResponseModel global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::Genesis.Net.Entities.Responses.RetrievalResponseModel>.MixinInstance {
			get {
				return __mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "authorization_code")]
		public global::System.String AuthorizationCode {
			get {
				return __mixins.Genesis_Net_Entities_Responses_AuthorizationModel.AuthorizationCode;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_AuthorizationModel.AuthorizationCode = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlIgnoreAttribute]
		public global::Genesis.Net.TransactionTypes TransactionType {
			get {
				return __mixins.Genesis_Net_Entities_Responses_TransactionTypeModel.TransactionType;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_TransactionTypeModel.TransactionType = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "transaction_type")]
		public global::System.String ProxyTransactionType {
			get {
				return __mixins.Genesis_Net_Entities_Responses_TransactionTypeModel.ProxyTransactionType;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_TransactionTypeModel.ProxyTransactionType = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "customer_email")]
		public global::System.String CustomerEmail {
			get {
				return __mixins.Genesis_Net_Entities_Responses_CustomerModel.CustomerEmail;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_CustomerModel.CustomerEmail = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "customer_phone")]
		public global::System.String CustomerPhone {
			get {
				return __mixins.Genesis_Net_Entities_Responses_CustomerModel.CustomerPhone;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_CustomerModel.CustomerPhone = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "type")]
		public global::System.String Type {
			get {
				return __mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.Type;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.Type = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "arn")]
		public global::System.String Arn {
			get {
				return __mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.Arn;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.Arn = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlIgnoreAttribute]
		public global::System.DateTime PostDate {
			get {
				return __mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.PostDate;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.PostDate = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "post_date")]
		public global::System.String ProxyPostDate {
			get {
				return __mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.ProxyPostDate;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.ProxyPostDate = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "reason_code")]
		public global::System.String ReasonCode {
			get {
				return __mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.ReasonCode;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.ReasonCode = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "reason_description")]
		public global::System.String ReasonDescription {
			get {
				return __mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.ReasonDescription;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.ReasonDescription = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "card_number")]
		public global::System.String CardNumber {
			get {
				return __mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.CardNumber;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.CardNumber = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "card_brand")]
		public global::System.String CardBrand {
			get {
				return __mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.CardBrand;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.CardBrand = value;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[System.Xml.Serialization.XmlElementAttribute (ElementName = "original_transaction_unique_id")]
		public global::System.String OriginalTransactionUniqueId {
			get {
				return __mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.OriginalTransactionUniqueId;
			}
			set {
				__mixins.Genesis_Net_Entities_Responses_RetrievalResponseModel.OriginalTransactionUniqueId = value;
			}
		}
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.__Shared
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.AuthorizationModel
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface IAuthorizationModelRequirements : global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.AuthorizationModel
{
	internal abstract class AuthorizationModelProtectedMembersWrapper : global::Genesis.Net.Entities.Responses.AuthorizationModel
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.AuthorizationModel
{
	internal class AuthorizationModelAbstractWrapper : AuthorizationModelProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.AuthorizationModel.IAuthorizationModelRequirements _target;
		public AuthorizationModelAbstractWrapper (global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.AuthorizationModel.IAuthorizationModelRequirements target) : base ()
		{
			_target = target;
		}
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.TransactionTypeModel
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ITransactionTypeModelRequirements : global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.TransactionTypeModel
{
	internal abstract class TransactionTypeModelProtectedMembersWrapper : global::Genesis.Net.Entities.Responses.TransactionTypeModel
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.TransactionTypeModel
{
	internal class TransactionTypeModelAbstractWrapper : TransactionTypeModelProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.TransactionTypeModel.ITransactionTypeModelRequirements _target;
		public TransactionTypeModelAbstractWrapper (global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.TransactionTypeModel.ITransactionTypeModelRequirements target) : base ()
		{
			_target = target;
		}
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.CustomerModel
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ICustomerModelRequirements : global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.CustomerModel
{
	internal abstract class CustomerModelProtectedMembersWrapper : global::Genesis.Net.Entities.Responses.CustomerModel
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.CustomerModel
{
	internal class CustomerModelAbstractWrapper : CustomerModelProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.CustomerModel.ICustomerModelRequirements _target;
		public CustomerModelAbstractWrapper (global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.CustomerModel.ICustomerModelRequirements target) : base ()
		{
			_target = target;
		}
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.RetrievalResponseModel
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface IRetrievalResponseModelRequirements : global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.RetrievalResponseModel
{
	internal abstract class RetrievalResponseModelProtectedMembersWrapper : global::Genesis.Net.Entities.Responses.RetrievalResponseModel
	{
	}
}
namespace pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.RetrievalResponseModel
{
	internal class RetrievalResponseModelAbstractWrapper : RetrievalResponseModelProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.RetrievalResponseModel.IRetrievalResponseModelRequirements _target;
		public RetrievalResponseModelAbstractWrapper (global::pMixins.AutoGenerated.Genesis.Net.Entities.Responses.RetrievalResponse.Genesis.Net.Entities.Responses.RetrievalResponseModel.IRetrievalResponseModelRequirements target) : base ()
		{
			_target = target;
		}
	}
}
